# -*- coding: utf-8 -*-
"""Question_Answer_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KjwvMOX2x66QTR9ZfVXARMpngzIU2Zd5
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/100_Unique_QA_Dataset.csv')

df.head()

# tokenize the dataset
def tokenize(text):
  text = text.lower()
  text = text.replace('?','')
  text = text.replace("'",'')
  return text.split()

vocab = {
    '<UNK>':0
}

# forming the vocab
def build_vocab(row):
  tokenize_q = tokenize(row['question'])
  tokenize_a = tokenize(row['answer'])
  merged_tokens = tokenize_a+tokenize_q

  for token in merged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

df.apply(build_vocab,axis=1)

vocab

# convert words to indexes

def text_to_indices(text,vocab):
  indexed_text = []
  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

text_to_indices('What is Omm',vocab)

import torch
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
  def __init__(self,df,vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):
    numerical_question = torch.tensor(text_to_indices(self.df.iloc[index]['question'],self.vocab),dtype=torch.long)
    numerical_answer = torch.tensor(text_to_indices(self.df.iloc[index]['answer'],self.vocab),dtype=torch.long)
    return numerical_question,numerical_answer

dataset = CustomDataset(df,vocab)

dataset[0]

dataloader = DataLoader(dataset,batch_size=1,shuffle =True)

for question,answer in dataloader:
  print(question,answer)

"""# Rnn Architecture
1. input_layer = 50 neuron vector  dimsenion (50)
2. hidden layer = 64 neuron
3. output = 320 neuron vocab-size


"""

import torch.nn as nn

class SimpleRNN(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,embedding_dim=50)
    self.rnn = nn.RNN(50,64,batch_first=True)
    self.output = nn.Linear(64,vocab_size)

  def forward(self,question):
    embed = self.embedding(question)
    hidden,final = self.rnn(embed)
    out = self.output(final[-1])
    return out

lr = 0.001
epochs = 20

model = SimpleRNN(len(vocab))

loss = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr = lr)

for epoch in range(epochs):
  total_loss = 0
  for question,answer in dataloader:
    optimizer.zero_grad()
    pred = model(question)
    loss = loss(pred,answer[0])
    loss.backward()
    optimizer.step()

    total_loss = total_loss+loss.item()

  print(f"epoch:{epoch+1},Loss:{total_loss:4f}")

